services:
  upscaler:
    build: .
    container_name: image-upscaler-api
    runtime: ${DOCKER_RUNTIME:-runc}
    ports:
      - "8124:8000"
    env_file:
      - .env
    environment:
      DEVICE: ${DEVICE:-cpu}
      GPU_ID: ${GPU_ID:-0}
      HALF_PRECISION: ${HALF_PRECISION:-true}
      CPU_THREADS: ${CPU_THREADS:-0}
      CPU_INTEROP_THREADS: ${CPU_INTEROP_THREADS:-0}
      CV_THREADS: ${CV_THREADS:-0}
      DEFAULT_TILE: ${DEFAULT_TILE:-0}
      TILE_PAD: ${TILE_PAD:-10}
      PRE_PAD: ${PRE_PAD:-0}
      JPEG_QUALITY: ${JPEG_QUALITY:-95}
      WEBP_QUALITY: ${WEBP_QUALITY:-95}
      MODEL: ${MODEL:-RealESRGAN_x4plus.pth}